init :
    visualization : true
    
setting :
    flight_height_limit : 10
    extra_obstacle_height : 0.0
    allowed_ground_height : -100.0
    laser_scan_step : 0.2
    laser_scan_resolution : 0.0
    
map :
    visualization_duration : 1
    observation_radius : 1000.0
    log_odd :
        min : -2.0
        max : 6.5
        occupy : 0.0
        hit : 3.05
        miss : -0.3
    boundary :
        lower_x : -20.0
        upper_x : 20.0
        lower_y : -20.0
        upper_y : 20.0
        lower_z : 0.0
        upper_z : 40.0
    safe_margin : 0.4
    dislike_margin : 0.7
    map_duration : 1000000
    resolution : 0.2
    path_resolution : 0.2
    dislike_factor : 10.0
    
max_velocity : 1.3
max_acceleration : 1.2
flight_velocity : 4.1
flight_acceleration : 4.1
path : 
    heuristic_ratio : 2.0
    allowed_ground : 0.0
    allowed_top : 1.8
